### PR TITLE
Proposal: drop linear gradient dependency in favor of generic element prop.

### PR DESCRIPTION
**Pull request by alekhinen**
## Description

Hey! I've been using this library in production and have been quite happy with it. However, one thing that's been bothering my team is the required dependency for `react-native-linear-gradient`. We're using `react-native-svg` for vector definitions and would rather pass through our own gradients defined by that library instead of using another one. 

My proposal here is to drop `react-native-linear-gradient` as a required dependency for this project and allow for a generic `imageForeground` property to pass through.

Updated the examples to show how this would work. 

## Sample Images

Kapture 2020-08-28 at 15 48 56

### CODE REVIEW

**Comment by alekhinen** [comment]
@hamidhadi let me know what you think of this!

**Comment by hamidhadi** [comment]
Hey @alekhinen, 
Thanks for the PR. It's good to remove the RNGradient from the dependencies. 
Could you please change the base branch to develop? I can do some changes and merge it to master then. 🙂

**Comment by alekhinen** [comment]
@hamidhadi done! 😃

**Comment by alekhinen** [comment]
ping @hamidhadi

**Pull request merged**
